require:
  # Pretend that regexps aren't mutable. They *mostly* aren't already and
  # we think it is more idiomatic not to freeze them all over the place.
  - ../resources/asciidoctor/style/pretend_regexp_isnt_mutable.rb

AllCops:
  TargetRubyVersion: 2.3

# The blocks in context and describe can be pretty long and that is ok.
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_context']
