require:
  # Pretend that regexps aren't mutable. They *mostly* aren't already and
  # we think it is more idiomatic not to freeze them all over the place.
  - ./resources/style/pretend_regexp_isnt_mutable.rb

AllCops:
  TargetRubyVersion: 2.3
  CacheRootDirectory: .rubocop_cache
  MaxFilesInCache: 1000

Style/ReturnNil:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 20

# The blocks in context and describe can be pretty long and that is ok.
Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - file_context
    - page_context
    - shared_context
    - shared_examples

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
