---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-docs
  description: Build the docs
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/docs-build

spec:
  type: buildkite-pipeline
  owner: group:docs
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: docs / build
    spec:
      repository: elastic/docs
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        docs-build-guild:
          access_level: MANAGE_BUILD_AND_READ
        ci-docs-migration-taskforce:
          access_level: MANAGE_BUILD_AND_READ
        docs:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: "true"
        SLACK_NOTIFICATIONS_CHANNEL: "#docs-builds"
        SLACK_NOTIFICATIONS_ALL_BRANCHES: "false"
        SLACK_NOTIFICATIONS_ON_SUCCESS: "false"

# Declare daily preview cleaner
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-docs-preview-cleaner
  description: Daily Preview Cleaner
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/docs-preview-cleaner

spec:
  type: buildkite-pipeline
  owner: group:docs
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: docs / preview-cleaner
    spec:
      repository: elastic/docs
      pipeline_file: ".buildkite/preview_cleaner_pipeline.yml"
      provider_settings:
        trigger_mode: none
      teams:
        docs-build-guild:
          access_level: MANAGE_BUILD_AND_READ
        ci-docs-migration-taskforce:
          access_level: MANAGE_BUILD_AND_READ
        docs:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

# Declare test execution on PR and merge to main
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-docs-test
  description: PR and Merge-to-Main Test
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/docs-test

spec:
  type: buildkite-pipeline
  owner: group:docs
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: docs-test
    spec:
      branch_configuration: "main"
      repository: elastic/docs
      pipeline_file: ".buildkite/pr_main_mr_test.yml"
      teams:
        docs-build-guild:
          access_level: MANAGE_BUILD_AND_READ
        ci-docs-migration-taskforce:
          access_level: MANAGE_BUILD_AND_READ
        docs:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
        SLACK_NOTIFICATIONS_CHANNEL: '#docs-builds'
        SLACK_NOTIFICATIONS_ALL_BRANCHES: 'false'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'


# Declare build air-gapped
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-docs-build-air-gapped
  description: Build air-gapped
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/docs-build-air-gapped

spec:
  type: buildkite-pipeline
  owner: group:docs
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: docs / build air-gapped
    spec:
      repository: elastic/docs
      pipeline_file: ".buildkite/air_gapped_pipeline.yml"
      provider_settings:
        trigger_mode: none
      teams:
        docs-build-guild:
          access_level: MANAGE_BUILD_AND_READ
        ci-docs-migration-taskforce:
          access_level: MANAGE_BUILD_AND_READ
        docs:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
