#!/usr/bin/env perl

use FindBin;

BEGIN {
    chdir "$FindBin::RealBin/";
}

use lib 'lib';
use File::Which;

binmode( STDIN,  ":utf8" );
binmode( STDOUT, ":utf8" );
binmode( STDERR, ":utf8" );

for (qw(2.7 2.6 2.5 2.4 2.3)) {
    my $path = which("python$_") or next;
    exec( $path, @ARGV );
}

die "Couldn't find python2.3-python2.7";
