---
version: "3.7"

services:
  # Run build.sh first to build latest image from source
  elastic-docs:
    container_name: elastic-docs
    image: docker.elastic.co/docs-private/air_gapped:latest
    ports:
      - 8000:8000/tcp
