require:
  # Pretend that regexps aren't mutable. They *mostly* aren't already and
  # we think it is more idiomatic not to freeze them all over the place.
  - ./style/pretend_regexp_isnt_mutable.rb

AllCops:
  TargetRubyVersion: 2.3

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Entries below are temporary while we work to enable or reconfigure them

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
