inherit_from: ../../.rubocop.yml

# Entries below are temporary while we work to enable or reconfigure them

AllCops:
  Exclude:
    # This file comes from asciidoctor's source and it is *fairly* temporary.
    - lib/docbook45/converter.rb

Metrics/AbcSize:
  Exclude:
    - lib/elastic_compat_tree_processor/extension.rb

Metrics/MethodLength:
  Exclude:
    - lib/elastic_compat_preprocessor/extension.rb
    - lib/elastic_include_tagged/extension.rb
