AllCops:
  TargetRubyVersion: 2.3

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Entries below are temporary while we work to enable or reconfigure them

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
