inherit_from: ../../.rubocop.yml

# Entries below are temporary while we work to enable or reconfigure them

AllCops:
  Exclude:
    # This file comes from asciidoctor's source and it is *fairly* temporary.
    - lib/docbook45/converter.rb
