inherit_from: ../../.rubocop.yml

# Entries below are temporary while we work to enable or reconfigure them

Layout/AlignParameters:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
