inherit_from: ../../.rubocop.yml

# Entries below are temporary while we work to enable or reconfigure them

Layout/AlignParameters:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
