env:
  USE_HTTPS_CLONE: true

steps:
  - key: "cancel-existing-builds"
    command: ".buildkite/scripts/cancel_running_pr.sh || true"
  - key: "build-pr-setup"
    label: "setup"
    command: ".buildkite/scripts/build_pr_commit_status.sh pending"
  - key: "build-pr"
    label: ":hammer: Build docs PR"
    command: ".buildkite/scripts/build_pr.sh"
    depends_on:
      - step: build-pr-setup
        allow_failure: true
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
      machineType: ${BUILD_MACHINE_TYPE}
  - key: "teardown"
    label: "teardown"
    command: |
      if [ $(buildkite-agent step get "outcome" --step "build-pr") == "passed" ]; then
        .buildkite/scripts/build_pr_commit_status.sh success
      else
        .buildkite/scripts/build_pr_commit_status.sh failure
      fi
    depends_on:
      - step: "build-pr"
  - wait
  - key: "branch-comparison"
    label: "Compare branches"
    command: |
      .buildkite/scripts/compare_bk_jenkins_branches.sh ${GITHUB_PR_BASE_REPO}_bk_${GITHUB_PR_NUMBER} ${GITHUB_PR_BASE_REPO}_${GITHUB_PR_NUMBER}
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
