steps:
  - key: "build-pr-setup"
    label: "setup"
    command: ".buildkite/scripts/build_pr_commit_status.sh pending"
    plugins:
      - elastic/vault-secrets#v0.0.2:
          path: "secret/ci/elastic-docs/docker.elastic.co" #"secret/ci/elastic-docs/docs_preview_cleaner"
          field: "username" #"value"
          env_var: "DOCKER_REGISTRY_USERNAME"

      - elastic/vault-secrets#v0.0.2:
          path: "secret/ci/elastic-docs/docs_preview_cleaner"
          field: "value"
          depth: 1
  - key: "build-pr"
    label: ":hammer: Build docs PR"
    command: echo "hello" #".buildkite/scripts/build_pr.sh"
    depends_on:
      - step: build-pr-setup
        allow_failure: true
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
  - key: "teardown"
    label: "teardown"
    command: |
      if [ $(buildkite-agent step get "outcome" --step "build-pr") == "passed" ]; then
        .buildkite/scripts/build_pr_commit_status.sh success
      else
        .buildkite/scripts/build_pr_commit_status.sh failure
      fi
    depends_on:
      - step: "build-pr"
