steps:
  - command: .buildkite/scripts/build_pr_setup.sh
    soft_fail:
      - exit_status: true
  - label: ":white_check_mark: Build docs PR"
    key: "build"
    command: |
      bash .buildkite/scripts/build_pr.sh
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
  - command: .buildkite/scripts/build_pr_teardown.sh
    exit_status: true
    depends_on: "build"
    allow_dependency_failure: true
    soft_fail:
      - exit_status: true
