steps:
  - key: "build-pr-setup"
    label: "setup"
    command: ".buildkite/scripts/build_pr_commit_status.sh pending"
  - key: "build-pr"
    label: ":hammer: Build docs PR"
    command: ".buildkite/scripts/build_pr.sh"
    depends_on:
      - step: build-pr-setup
        allow_failure: true
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
  - key: "teardown"
    label: "teardown"
    command: |
      if [ $(buildkite-agent step get "outcome" --step "build-pr") == "passed" ]; then
        .buildkite/scripts/build_pr_commit_status.sh success
      else
        .buildkite/scripts/build_pr_commit_status.sh failure
      fi
    depends_on:
      - step: "build-pr"
