steps:
  - key: "build-pr-setup"
    label: "setup"
    command: .buildkite/scripts/build_pr_setup.sh
  - key: "build-pr"
    label: ":hammer: Build docs PR"
    command: .buildkite/scripts/build_pr.sh
    depends_on:
      - step: build-pr-setup
        allow_failure: true
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
  - command: .buildkite/scripts/build_pr_teardown.sh
    label: "teardown"
    depends_on:
      - step: "build-pr"
        allow_failure: true
