steps:
  - label: ":white_check_mark: Build docs PR"
    command: |
      bash .buildkite/scripts/build_pr.sh
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
notify:
  - email: "docs-status@elastic.co"
    if: build.state == "failed"
