steps:
  - label: "Execute tests"
    command: ".buildkite/scripts/test.sh"
    if: build.branch == "master" || build.env("BUILDKITE_PULL_REQUEST") != "false"
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
notify:
  - email: "docs-status@elastic.co"
    if: build.state == "failed"
