env:
  USE_HTTPS_CLONE: true

steps:
  - key: "cancel-existing-builds"
    command: ".buildkite/scripts/cancel_running_pr.sh || true"
  - key: "build-pr-setup"
    label: "setup"
    command: |
      curl -s -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${VAULT_GITHUB_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/repos/${GITHUB_PR_BASE_OWNER}/${GITHUB_PR_BASE_REPO}/statuses/${GITHUB_PR_TRIGGERED_SHA}" \
        -d '{"state":"'pending'","target_url":"'$BUILDKITE_BUILD_URL'","description":"'Build started'","context":"buildkite/'$BUILDKITE_PIPELINE_SLUG'"}'
    plugins:
      - 'uber-workflow/run-without-clone':
  - key: "build-pr"
    label: ":hammer: Build docs PR"
    command: ".buildkite/scripts/build_pr.sh"
    depends_on:
      - step: build-pr-setup
        allow_failure: true
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
      diskSizeGb: 150
      machineType: ${BUILD_MACHINE_TYPE}
  - key: "teardown"
    label: "teardown"
    command: |
      status_state=failure
      if [ $(buildkite-agent step get "outcome" --step "build-pr") == "passed" ]; then
        status_state=success
      fi
      curl -s -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${VAULT_GITHUB_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/repos/${GITHUB_PR_BASE_OWNER}/${GITHUB_PR_BASE_REPO}/statuses/${GITHUB_PR_TRIGGERED_SHA}" \
        -d '{"state":"'$status_state'","target_url":"'$BUILDKITE_BUILD_URL'","description":"Build finished","context":"buildkite/'$BUILDKITE_PIPELINE_SLUG'"}'
    depends_on:
      - step: "build-pr"
        allow_failure: true
    plugins:
      - 'uber-workflow/run-without-clone':
