steps:
  - label: 'Clone built-docs'
    command: |
      git clone git@github.com:elastic/built-docs --branch master --depth 1
  - label: 'ls'
    command: |
      ls
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
      diskSizeGb: 150
      machineType: n2-standard-4
# notify:
#   - email: "docs-status@elastic.co"
#     if: build.state == "failed"
