steps:
  - label: "Execute tests"
    command: |
      bash .buildkite/scripts/test.sh
#    branches: "master"
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
notify:
  - email: "docs-status@elastic.co"
    if: build.state == "failed"