steps:
  - label: "Execute tests"
    command: ".buildkite/scripts/test.sh"
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
notify:
  - email: "docs-status@elastic.co"
    if: build.state == "failed" && build.branch == "master"
