name: 'docs-preview'
description: 'Add docs-preview comment in the given repository.'
inputs:
  repo:
    description: 'the name of the repository'
    required: true
  pr:
    description: 'the pull-request'
    required: true
  github-token:
    description: 'The GitHub access token.'
    required: true
  preview-path:
    description: 'Path to append to base doc url in preview link'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        REPO: ${{ inputs.repo }}
        PR: ${{ inputs.pr }}
        PREVIEW_PATH: ${{ inputs.preview-path }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { REPO, PR, PREVIEW_PATH } = process.env

          const comment = `A documentation preview will be available soon.
          Help us out by validating the Buildkite preview and reporting issues [here](https://github.com/elastic/docs/issues/new?labels=buildkite-migration,bug).

            - 🔨 Buildkite [builds](https://buildkite.com/elastic/docs-build-pr/builds?meta_data[repo_pr]=${REPO}_${PR})
            - 📚 HTML diff: [Buildkite](https://${REPO}_bk_${PR}.docs-preview.app.elstc.co/diff)  - [Jenkins](https://${REPO}_${PR}.docs-preview.app.elstc.co/diff)
            - 📙 Preview: [Buildkite](https://${REPO}_bk_${PR}.docs-preview.app.elstc.co/${PREVIEW_PATH})  -  [Jenkins](https://${REPO}_${PR}.docs-preview.app.elstc.co/${PREVIEW_PATH})
            - 🧪 [Buildkite vs Jenkins diff](https://github.com/elastic/built-docs/compare/${REPO}_bk_${PR}..${REPO}_${PR})

           <details>
            <summary>Triggering rebuilds</summary>
        You can manually trigger a new Buildkite build with any of the below commands:
          \`\`\`
run docs-build
run docs-build rebuild
run docs-build warnlinkcheck
run docs-build skiplinkcheck (takes precedence over the warnlinkcheck option)
buildkite test this
buildkite test this rebuild
buildkite test this warnlinkcheck
buildkite test this skiplinkcheck 
          \`\`\`
          </details>
          `;

          github.rest.issues.createComment({
            issue_number: PR,
            owner: 'elastic',
            repo: REPO,
            body: comment,
          });
