[[sample-api]]
=== Sample API
++++
<titleabbrev>Sample</titleabbrev>
++++

Creates a cool thing.

////
Use the appropriate heading levels for your book.
Add anchors for each section.
FYI: The section titles use attributes in case those terms change.
////
[float]
[[sample-api-request]]
==== {api-request-title}
////
This section show the basic endpoint, without the body or optional parameters.
Variables should use <...> syntax.
If an API supports both PUT and POST, include both here.
////

`PUT /<follower_index>/_ccr/follow`

[float]
[[sample-api-prereqs]]
==== {api-prereq-title}
////
Optional list of prerequisites.

For example:

* A snapshot of an index created in 5.x can be restored to 6.x. You must...
* If the {es} {security-features} are enabled, you must have `write`, `monitor`,
and `manage_follow_index` index privileges...
////

[float]
[[sample-api-desc]]
==== {api-description-title}
////
Add a more detailed description the context.
Link to related APIs if appropriate.

Guidelines for parameter documentation
***************************************
* Use a definition list.
* End each definition with a period.
* Each parameter should be marked as Optional or Required.
* Include the data type.
* Include default values as the last sentence of the first paragraph.
* Include a range of valid values, if applicable.
* If the parameter requires a specific delimiter for multiple values, say so.
* If the parameter supports wildcards, ditto.
* For objects or nested objects, link to a separate definition list.
***************************************
////

[float]
[[sample-api-path-params]]
==== {api-path-parms-title}
////
A list of all path parameters in the endpoint request.

For example:
`<follower_index>` (Required)::
(string) Name of the follower index
////

[float]
[[sample-api-query-params]]
==== {api-query-parms-title}
////
A list of optional query parameters.

For example:
`wait_for_active_shards` (Optional)::
(integer) Specifies the number of shards to wait on being active before
responding. A shard must be restored from the leader index being active.
Restoring a follower shard requires transferring all the remote Lucene segment
files to the follower index. The default is `0`, which means waiting on none of
the shards to be active.
////

[float]
[[sample-api-request-body]]
==== {api-request-body-title}
////
A list of the properties you can specify in the body of the request.

For example:
`remote_cluster` (Required)::
(string) <<modules-remote-clusters,Remote cluster>> containing the leader
index.

`leader_index` (Required)::
(string) the name of the index in the leader cluster to follow.
////

////
[[sample-api-response-body]]
==== {api-response-body-title}
Response body is only required for detailed responses.
////

////
[[sample-api-response-codes]]
==== {api-response-codes-title}
Response codes are only required when needed to understand the response body.

For example:
`200`::
Indicates all listed indices or index aliases exist.

 `404`::
Indicates one or more listed indices or index aliases **do not** exist.
////

[float]
[[sample-api-example]]
==== {api-example-title}
////
Optional brief example.
Use an 'Examples' heading if you include multiple examples.


[source,js]
----
PUT /follower_index/_ccr/follow?wait_for_active_shards=1
{
  "remote_cluster" : "remote_cluster",
  "leader_index" : "leader_index",
  "max_read_request_operation_count" : 1024,
  "max_outstanding_read_requests" : 16,
  "max_read_request_size" : "1024k",
  "max_write_request_operation_count" : 32768,
  "max_write_request_size" : "16k",
  "max_outstanding_write_requests" : 8,
  "max_write_buffer_count" : 512,
  "max_write_buffer_size" : "512k",
  "max_retry_delay" : "10s",
  "read_poll_timeout" : "30s"
}
----
// CONSOLE
// TEST[setup:remote_cluster_and_leader_index]

The API returns the following result:

[source,js]
----
{
  "follow_index_created" : true,
  "follow_index_shards_acked" : true,
  "index_following_started" : true
}
----
// TESTRESPONSE
////