---
name: test-docs-preview

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  doc-preview-pr:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/docs/.github/actions/docs-preview@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          pr: ${{ github.event.pull_request.number }}

  doc-preview-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/docs/.github/actions/docs-preview@action-update
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          preview-path: 'guide/en/observability/master/index.html'
          pr: 2865
