name: Patch release version bump docs
on:
  workflow_dispatch:
   inputs:
      MAJOR_VERSION:
        type: choice
        description: 'Major version'
        options: ['7', '8']
      MINOR_VERSION:
        type: choice
        description: 'Minor version'
        options: ['12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25']
      PATCH_VERSION:
        type: choice
        description: 'Patch version (new)'
        options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25']

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version
        run: |
            RELEASE_VERSION=${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}.${{ github.event.inputs.PATCH_VERSION }}
            RELEASE_VERSION_PREV=${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}.$(( ${{ github.event.inputs.PATCH_VERSION }} -1 ))
            RELEASE_SHORT=${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}
            STACK_VERSION_FILE="./shared/versions/stack/${RELEASE_SHORT}.asciidoc"
            sed -i "s/$RELEASE_VERSION_PREV/$RELEASE_VERSION/g" ${STACK_VERSION_FILE}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-version
          branch-suffix: short-commit-hash
          commit-message: "bump version to ${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}.${{ github.event.inputs.PATCH_VERSION }}"
          title: "Bump version to ${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}.${{ github.event.inputs.PATCH_VERSION }}"
          body: >
            This PR is auto-generated. Do not merge until the ${{ github.event.inputs.MAJOR_VERSION }}.${{ github.event.inputs.MINOR_VERSION }}.${{ github.event.inputs.PATCH_VERSION }} release.
